"""Made ride_date nullable in book_ride

Revision ID: 3320b0632d31
Revises: 
Create Date: 2025-03-04 02:26:43.085844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3320b0632d31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_ride', schema=None) as batch_op:
        batch_op.alter_column('ride_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_ride', schema=None) as batch_op:
        batch_op.alter_column('ride_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
