"""Added ride_date to RideRating model

Revision ID: 71accbd6d11e
Revises: 8b35df2f4f3d
Create Date: 2025-04-06 17:11:52.316755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71accbd6d11e'
down_revision = '8b35df2f4f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_rating', schema=None) as batch_op:
        batch_op.drop_constraint('unique_ride_passenger_rating', type_='unique')
        batch_op.create_unique_constraint('unique_rating_per_day', ['ride_id', 'passenger_id', 'ride_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_rating', schema=None) as batch_op:
        batch_op.drop_constraint('unique_rating_per_day', type_='unique')
        batch_op.create_unique_constraint('unique_ride_passenger_rating', ['ride_id', 'passenger_id'])

    # ### end Alembic commands ###
