"""new column in book_ride

Revision ID: 7cbf6146d92d
Revises: 
Create Date: 2025-03-09 23:52:37.593483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbf6146d92d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_ride', schema=None) as batch_op:
        batch_op.drop_column('cancellation_timestamp')

    # ### end Alembic commands ###
