"""Add journey_status to book_ride

Revision ID: 81b0150ac114
Revises: 71accbd6d11e
Create Date: 2025-04-06 23:20:40.688719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b0150ac114'
down_revision = '71accbd6d11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journey_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_ride', schema=None) as batch_op:
        batch_op.drop_column('journey_status')

    # ### end Alembic commands ###
