"""Added ride_date to RideRating model

Revision ID: 8b35df2f4f3d
Revises: 
Create Date: 2025-04-06 16:55:08.633013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b35df2f4f3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ride_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_rating', schema=None) as batch_op:
        batch_op.drop_column('ride_date')

    # ### end Alembic commands ###
