"""Add seen_by_receiver to ChatMessage

Revision ID: da4106a7ad4d
Revises: e8e0bf91046d
Create Date: 2025-04-02 16:43:29.864013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4106a7ad4d'
down_revision = 'e8e0bf91046d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen_by_receiver', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('seen_by_receiver')

    # ### end Alembic commands ###
