"""Added passenger-driver flexibility

Revision ID: f35c8978170b
Revises: 04ed8d158354
Create Date: 2025-02-24 01:14:48.862692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35c8978170b'
down_revision = '04ed8d158354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passengers_rides')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=10), nullable=False))

    op.create_table('passengers_rides',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('ride_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['publish_ride.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ride_id')
    )
    # ### end Alembic commands ###
