name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Runs the workflow when pushing to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on GitHub's Ubuntu environment

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to PythonAnywhere
      env:
        PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USERNAME: "Sreejachowdaryt"  # Replace with your actual PythonAnywhere username
      run: |
        curl -X POST --user "$PA_USERNAME:$PYTHONANYWHERE_API_TOKEN" \
        "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/$PA_USERNAME.pythonanywhere.com/reload/"
